import { cdnImages } from "./image-data";

// Additional gallery images from the "GALLERIA PLUS per 3forketet" folder
export const galleryPlusImages = [
  {
    src: "/images/GALLERIA PLUS per 3forketet/brizo-tre-forchette.jpg",
    alt: "Brizo Tre Forchette signature dish",
    title: "Brizo Tre Forchette",
    category: "Signature",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/caption.jpg",
    alt: "Elegant table setting with fine dining presentation",
    title: "Fine Dining Experience",
    category: "Ambiance",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/caption (1).jpg",
    alt: "Chef's special presentation with artistic plating",
    title: "Chef's Special",
    category: "Signature",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/caption (2).jpg",
    alt: "Seasonal delicacy with fresh ingredients",
    title: "Seasonal Delicacy",
    category: "Specials",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/caption (3).jpg",
    alt: "Artisanal pasta dish with premium ingredients",
    title: "Artisanal Pasta",
    category: "Primi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/caption (4).jpg",
    alt: "Gourmet seafood platter with chef's selection",
    title: "Gourmet Seafood Platter",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },

  {
    src: "/images/GALLERIA PLUS per 3forketet/caption (6).jpg",
    alt: "Exclusive chef's tasting menu item",
    title: "Chef's Tasting Menu",
    category: "Specials",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/desserts.jpg",
    alt: "Assortment of Italian desserts and sweet treats",
    title: "Italian Desserts",
    category: "Dolci",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/fish-eggs-pasta.jpg",
    alt: "Luxurious pasta with fish eggs and premium ingredients",
    title: "Caviar Pasta",
    category: "Primi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/linguine-with-seafood.jpg",
    alt: "Linguine with fresh seafood in rich sauce",
    title: "Seafood Linguine",
    category: "Primi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/our-staff.jpg",
    alt: "Our professional and friendly restaurant staff",
    title: "Our Staff",
    category: "Team",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  // New screenshots added July 2025
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 174902.jpg",
    alt: "Elegant dining presentation with fine cuisine",
    title: "Elegant Dining Experience",
    category: "Dining Experience",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175039.jpg",
    alt: "Artistically plated seafood dish with garnishes",
    title: "Seafood Artistry",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175112.jpg",
    alt: "Gourmet pasta with premium ingredients",
    title: "Gourmet Pasta Creation",
    category: "Primi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175202.jpg",
    alt: "Exquisite appetizer with delicate presentation",
    title: "Exquisite Appetizer",
    category: "Antipasti",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175222.jpg",
    alt: "Chef's special seafood creation",
    title: "Chef's Seafood Special",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175245.jpg",
    alt: "Seasonal fish dish with complementary garnishes",
    title: "Seasonal Fish Creation",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175307.jpg",
    alt: "Artisanal dessert with elegant presentation",
    title: "Artisanal Dessert",
    category: "Dolci",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175325.jpg",
    alt: "Signature pasta dish with premium sauce",
    title: "Signature Pasta",
    category: "Primi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175352.jpg",
    alt: "Gourmet meat dish with artistic presentation",
    title: "Gourmet Meat Creation",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175429.jpg",
    alt: "Seafood specialty with chef's touch",
    title: "Seafood Specialty",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175535.jpg",
    alt: "Premium steak with complementary sides",
    title: "Premium Steak",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175601.jpg",
    alt: "Delicate fish dish with seasonal vegetables",
    title: "Delicate Fish Creation",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175632.jpg",
    alt: "Artistically plated appetizer with premium ingredients",
    title: "Artistic Appetizer",
    category: "Antipasti",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175659.jpg",
    alt: "Signature seafood dish with chef's special sauce",
    title: "Signature Seafood",
    category: "Secondi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175714.jpg",
    alt: "Gourmet pasta with premium seafood",
    title: "Gourmet Seafood Pasta",
    category: "Primi",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  },
  {
    src: "/images/GALLERIA PLUS per 3forketet/Screenshot 2025-07-03 175728.jpg",
    alt: "Chef's special creation with seasonal ingredients",
    title: "Chef's Seasonal Special",
    category: "Signature",
    cdnFallback: "fallbackDish" as keyof typeof cdnImages,
  }
];
